### ISSUE TITLE
Error when attempting to delete registry with bad data in the db

### ISSUE THREAD

**Issue by jlk** [LayeredInsight/runtime-api-example-python#20]
This could be a little more polite:

```
(venv) runtime-api-example-python develop $ ./li_delete_registry  --name "johns docker.io"
Traceback (most recent call last):
  File "./li_delete_registry", line 32, in <module>
    registry = registry_api.get_registry_by_name(args.name)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/apis/registry_api.py", line 953, in get_registry_by_name
    (data) = self.get_registry_by_name_with_http_info(registry_name, **kwargs)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/apis/registry_api.py", line 1026, in get_registry_by_name_with_http_info
    collection_formats=collection_formats)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/api_client.py", line 326, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/api_client.py", line 239, in deserialize
    return self.__deserialize(data, response_type)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/api_client.py", line 631, in __deserialize_model
    instance = klass(**kwargs)
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/models/registry.py", line 83, in __init__
    self.type = type
  File "/src/github.com/layeredinsight/runtime-api-example-python/venv/lib/python2.7/site-packages/layint_runtime_api/models/registry.py", line 230, in type
    .format(type, allowed_values)
ValueError: Invalid value for `type` (), must be one of ['dtr', 'ecr', 'docker.io', 'quay.io', 'private']
```

**Comment by PrasadG193** [comment]
Hi @jlk, couldn't repro this issue. I think it is already fixed
```
$ ./li_delete_registry --name "invalid name"
Exception when calling RegistryApi->get_registry_by_name: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 24 Sep 2018 10:56:37 GMT', 'Vary': 'Origin', 'Content-Length': '199', 'Content-Type': 'application/json', 'Layered-Insight-Request-Id': 'RQ371bf10000000012'})
HTTP response body: {"Code":10404,"Message":"Resource not found","MessageInfo":"For error definition see: /v0.01/errors","Status":404,"Error":"Unable to service GET request for /v0.01/Registries/ByName/invalid%20name"}
````

**Comment by jlk** [comment]
ok, closing for now.
